### PR TITLE
Ft add language switcher

### PR DESCRIPTION
**Pull request by esirK**
Adds a UI change to allow switching between different platform languages.

#### Screenshot
Screenshot 2022-02-03 at 13 12 18

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏽 ... looks good

----

1. I think the location needs to change to either top left in the navbar (pushing Tenders and Spending Analysis to the left a bit) or bottom left in the footer 
S
2. It should also be a form that you post so that a user doesn't get redirect to the home page every time you switch language ([docs](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#the-set-language-redirect-view))

**Comment by esirK** [comment]
> 👍🏽 ... looks good
> 
> 1. I think the location needs to change to either top left in the navbar (pushing Tenders and Spending Analysis to the left a bit) or bottom left in the footer
>    S
> 2. It should also be a form that you post so that a user doesn't get redirect to the home page every time you switch language ([docs](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#the-set-language-redirect-view))

For 1, I feel like we should have the switcher somewhere that the user can immediately see it top right/bottom seems kinda hidden somehow for me.
For 2 sure I'll update that.

**Comment by esirK** [comment]
This has been fixed @kilemensi

**Review by kilemensi — APPROVED** [review]
🚀

——-

Not sure why we have Pipfile changes in this PR.

**Comment by esirK** [comment]
@kilemensi  The Pipfile has been outdated and thus too many issues while trying to run the project using pipenv.
So this just updates it.

**Pull request merged**
